Whitelabel.UI/Models/ErrorViewModel.cs
namespace Whitelabel.UI.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Whitelabel.UI/Models/WhiteLabel/CreateWhiteLabelViewModel.cs
namespace Whitelabel.UI.Models.WhiteLabel;

public class CreateWhiteLabelViewModel
{
    public string BrandName { get; set; }
    public string PrimaryColor { get; set; }
    public string SecondaryColor { get; set; }
    public int TenantId { get; set; }
}

Whitelabel.UI/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Whitelabel.UI.Models;

namespace Whitelabel.UI.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Whitelabel.UI/Controllers/WhitelabelController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Whitelabel.Business.Services.SignalR;
using Whitelabel.Business.Services.WhiteLabel;
using Whitelabel.Core.Results.Base;
using Whitelabel.Domain.Dtos.Concrete;
using Whitelabel.Domain.Dtos.Concrete.WhiteLabel;

namespace Whitelabel.UI.Controllers;

[Route("whitelabel")]
public class WhitelabelController(ILogger<WhitelabelController> logger, IWebHostEnvironment web, IWhiteLabelService whiteLabelService, IHubContext<WhiteLabelHub> hubContext) : Controller
{
    private readonly ILogger<WhitelabelController> _logger = logger;
    private readonly IWebHostEnvironment _web = web;
    private readonly IHubContext<WhiteLabelHub> _hubContext = hubContext;


    public IActionResult GetDefaultCssFile()
    {
        // wwwroot klasörünün yolunu al
        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/css/default.css");
        var cssContent = System.IO.File.ReadAllText(filePath);
        return Content(cssContent, "text/css");

    }
    
    [HttpPost]
    [Route("create")]
    public async Task<IActionResult> Create()
    {
        var result = await whiteLabelService.CreateWhiteLabel(new CreateWhiteLabelRequestDto
        {
            BrandName = "Sec 2",
            PrimaryColor = "#0dfd11",
            SecondaryColor = "#dd0dfd",
            LogoUrl = "../../images/logo2.jpg",
            TenantId = 1
        });

        if (result.Status == StatusTypeEnum.Success)
        {
            await hubContext.Clients.All.SendAsync("RefreshPage");
        }

        return Json(new { isSuccess = result.Status == StatusTypeEnum.Success });

    }
    
    [HttpPost]
    [Route("reset")]
    public async Task<IActionResult> Reset()
    {
        var result = await whiteLabelService.ResetWhiteLabel(new ResetWhiteLabelRequestDto
        {
            TenantId = 1
        });
        
        if (result.Status == StatusTypeEnum.Success)
        {
            await hubContext.Clients.All.SendAsync("RefreshPage");
        }
        return Json(new { isSuccess = result.Status == StatusTypeEnum.Success });

    }
    
}

Whitelabel.UI/ViewComponents/CustomStyleViewComponent/CustomStyleViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Whitelabel.UI.ViewComponents.CustomStyleViewComponent;

public class CustomStyleViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        var tenantId = 1;
        var defaultCssFilePath = "wwwroot/css/variable.css";
        var tenantCssFilePath = $"wwwroot/css/{tenantId}/variable.css";
        
        if (File.Exists(tenantCssFilePath))
        {
            var tenantFullPath = Path.Combine(Directory.GetCurrentDirectory(), tenantCssFilePath);
            var tenantCssContent = File.ReadAllText(tenantFullPath);
            return View("_CustomerStyle",tenantCssContent);
        }
        var fullPath = Path.Combine(Directory.GetCurrentDirectory(), defaultCssFilePath);
        var defaultCssContent = File.ReadAllText(fullPath);
        return View("_CustomerStyle",defaultCssContent);
        
    }
}

Whitelabel.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <button onclick="handleOnClickTrigger()" class="sec-button">Trigger WhiteLabel</button>
    <button onclick="handleOnClickReset()" class="sec-button">Reset WhiteLabel</button>
    <div class="logo"></div>
</div>

<script src="~/js/whitelabel.js"></script>

Whitelabel.UI/Views/Shared/Components/CustomStyle/_CustomerStyle.cshtml
<!-- _CustomStyle.cshtml -->
@model string

<style id="custom-style">
    @Html.Raw(Model)
</style>

Whitelabel.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MvcAppTemplate</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    @await Component.InvokeAsync("CustomStyle")
    <link rel="stylesheet" href="~/css/default.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcAppTemplate</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - MvcAppTemplate - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/sweetalert2"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/6.0.1/signalr.js"></script>
<script src="~/js/signalR.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>